kind: Service
apiVersion: v1
metadata:
  name: naas
  namespace: nilorg
  labels:
    app: naas
spec:
  selector:
    app: naas
  ports:
    - name: naas-8080
      port: 8080
    - name: naas-5000
      port: 5000
    - name: naas-9000
      port: 9000